export const DISEASES = {
  'Black Sigatoka': {
    severity: 'high',
    emoji: '🍂',
    shortDesc: 'Fungal leaf disease — Mycosphaerella fijiensis',
    description: 'Causes dark streaks and lesions on leaves, significantly reducing photosynthesis and fruit yield.',
    recommendation: 'Apply systemic fungicide immediately. Remove all visibly infected leaves and destroy them. Improve airflow around plants.',
  },
  'Black Leaf Streak': {
    severity: 'high',
    emoji: '🍂',
    shortDesc: 'Fungal leaf streaking disease',
    description: 'Dark streaks/lesions appear on leaves, reducing photosynthesis and yield.',
    recommendation: 'Apply appropriate fungicide and improve airflow by spacing plants.',
  },
  'Banana Rust': {
    severity: 'medium',
    emoji: '🟠',
    shortDesc: 'Rust-like fungal spots',
    description: 'Rust-like spots can appear and spread across the plant/fruit surface.',
    recommendation: 'Remove infected parts and apply a suitable fungicide.',
  },
  'Banana Scab Moth': {
    severity: 'medium',
    emoji: '🦋',
    shortDesc: 'Pest damage on fruit surface',
    description: 'Surface scarring and damage caused by banana scab moth activity.',
    recommendation: 'Use targeted pest control and monitor with traps.',
  },
  'Crown Rot': {
    severity: 'medium',
    emoji: '🍌',
    shortDesc: 'Post-harvest fungal infection',
    description: 'Infection at the fruit crown, commonly after harvest and during storage.',
    recommendation: 'Improve storage conditions and consider post-harvest fungicide dips.',
  },
  'Fungal Disease': {
    severity: 'low',
    emoji: '🍄',
    shortDesc: 'General fungal infection',
    description: 'General fungal symptoms may appear on leaves or other plant parts.',
    recommendation: 'Maintain hygiene and apply broad-spectrum fungicide if needed.',
  },
  'Yellow Sigatoka': {
    severity: 'medium',
    emoji: '🌿',
    shortDesc: 'Fungal infection — Mycosphaerella musicola',
    description: 'Yellow spots that expand into brown streaks across the leaf surface.',
    recommendation: 'Apply copper-based fungicide. Monitor weekly. Ensure adequate nutrition for the plant.',
  },
  'Panama Disease': {
    severity: 'high',
    emoji: '🌱',
    shortDesc: 'Soil-borne fungal wilt — Fusarium oxysporum',
    description: 'Attacks root system and internal stem tissue causing yellowing and collapse.',
    recommendation: 'No chemical cure. Isolate affected plants immediately. Do not replant bananas in the same soil.',
  },
  'Banana Bunchy Top': {
    severity: 'high',
    emoji: '🍃',
    shortDesc: 'Viral disease — spread by aphids',
    description: 'Causes stunted growth with a bunched appearance at the crown of the plant.',
    recommendation: 'Remove and destroy infected plants entirely. Control aphid populations. Use virus-free planting material.',
  },
  'Moko Disease': {
    severity: 'high',
    emoji: '🌾',
    shortDesc: 'Bacterial wilt — Ralstonia solanacearum',
    description: 'Causes internal browning of fruit and vascular tissue, leading to plant collapse.',
    recommendation: 'Destroy infected plants by uprooting. Disinfect all tools with bleach. Restrict movement of plant material.',
  },
  'Healthy': {
    severity: 'none',
    emoji: '✅',
    shortDesc: 'No disease detected',
    description: 'The banana plant appears to be in excellent health with no visible signs of infection.',
    recommendation: 'Continue regular watering, fertilization, and monthly monitoring. Inspect leaves for early signs.',
  },
};

export const SEVERITY_CONFIG = {
  high:   { label: 'High Severity',   color: '#E53E3E', bg: '#FFF5F5' },
  medium: { label: 'Medium Severity', color: '#D97706', bg: '#FFFBEB' },
  low:    { label: 'Low Severity',    color: '#2B6CB0', bg: '#EBF8FF' },
  none:   { label: 'Healthy',         color: '#16A34A', bg: '#F0FDF4' },
};